services:
  backend-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      # Monta o diretório do projeto local no /app do contêiner para hot-reloading
      - ..:/app
      # Impede que o node_modules do host sobrescreva o do contêiner e vice-versa
      - /app/node_modules
